# <font color='blue'>Data Science Academy</font>
# <font color='blue'>Matemática Para Machine Learning</font>

## Lista de Exercícios  - Capítulo 8

O objetivo desta lista de exercícios é você praticar os principais conceitos estudados neste capítulo, ao mesmo tempo que desenvolve suas habilidades em lógica de programação com a linguagem Python. 

Caso tenha dúvidas, isso é absolutamente normal e faça um trabalho de pesquisa a fim de relembrar o formato das operações matemáticas.

Quando encontrar o formato de uma operação que resolva o exercício proposto, use a linguagem Python para representar esta operação. Em essência, é assim que aplicamos Matemática Para Machine Learning, construindo algoritmos e representando esses algoritmos em linguagem de programação.

Divirta-se!!

### Exercício 1 - Usando a função numpy.linalg.eigvals() do Numpy, calcule os autovalores da matriz abaixo.

In [1]:
# Solução
import numpy as np

m = np.matrix([[2, -1, 0],
               [-1, 2, -1],
               [0, -1, 2]])

eigenvalues = np.linalg.eigvals(m)
print("\nAutovalores: ", eigenvalues)


Autovalores:  [3.41421356 2.         0.58578644]


### Exercício 2 - Usando a função numpy.linalg.eig() do Numpy, calcule os autovalores e autovetores da matriz abaixo.

Dica: A função numpy.linalg.eig() retorna uma tupla que consiste em um vetor e uma matriz. O vetor (que pode ser representado por "autova") contém os autovalores. O array (que pode ser representado por "autove") contém os autovetores correspondentes, um autovetor por coluna. Os autovetores são normalizados para que suas normas euclidianas sejam 1.

Referência: https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.linalg.eig.html

In [2]:
# Solução
import numpy as np
from numpy import linalg as LA

A = np.array([[1,2,3],[3,2,1],[1,0,-1]])
autova, autove = LA.eig(A)

print("\nAutovalores: ", autova)
print("\nAutovetores: ", autove)


Autovalores:  [ 4.31662479e+00 -2.31662479e+00  1.47314580e-16]

Autovetores:  [[ 0.58428153  0.73595785  0.40824829]
 [ 0.80407569 -0.38198836 -0.81649658]
 [ 0.10989708 -0.55897311  0.40824829]]


### Exercício 3 - Usando as funções oferecidas pelo SymPy, calcule autovalores e autovetores da matriz abaixo.

In [3]:
# Solução
from sympy import *

A = Matrix([[0, 2], [1, -3]])

print("\nAutovalores: ", A.eigenvals())   # retorna autovalores e sua multiplicidade algébrica
print("\nAutovetores: ", A.eigenvects())  # retorna autovalores, autovetores


Autovalores:  {-sqrt(17)/2 - 3/2: 1, -3/2 + sqrt(17)/2: 1}

Autovetores:  [(-3/2 + sqrt(17)/2, 1, [Matrix([
[-2/(-sqrt(17)/2 + 3/2)],
[                     1]])]), (-sqrt(17)/2 - 3/2, 1, [Matrix([
[-2/(3/2 + sqrt(17)/2)],
[                    1]])])]


### Exercício 4 - Com base no exercício anterior, retorne apenas a lista de autovalores.

A.eigenvals () retorna {-sqrt (17) / 2 - 3/2: 1, -3/2 + sqrt (17) / 2: 1} que é um dicionário de autovalores e suas multiplicidades. Se você não precisa das multiplicidades, use list(A.eigenvals().Keys()) para obter uma lista simples de autovalores.

A saída de autovetores é um pouco mais complicada e consiste em triplos (autovalor, multiplicidade desse autovalor, base do autoespaço). Note que a multiplicidade é multiplicidade algébrica, enquanto o número de autovetores retornados é a multiplicidade geométrica, que pode ser menor. Os autovetores são retornados como matrizes de 1 coluna.

Para essa matriz, A.eigenvects() retorna o autovetor [-2 / (- sqrt (17) / 2 + 3/2), 1] para o autovalor -3/2 + sqrt (17) / 2, e autovetor [ -2 / (3/2 + sqrt (17) / 2), 1] para eigenvalue -sqrt (17) / 2 - 3/2.

Se você quiser os autovetores apresentados como listas simples de coordenadas, usamos list comprehension:

[list (tup [2] [0]) fro tup em A.eigenvects ()]

que geraria [[-2 / (- sqrt (17) / 2 + 3/2), 1], [-2 / (3/2 + sqrt (17) / 2), 1]]. (Note que apenas escolhe um autovetor para cada autovalor, o que nem sempre é o que você quer).

In [4]:
# Solução
from sympy import *

A = Matrix([[0, 2], [1, -3]])

print("\nAutovalores: ", list(A.eigenvals().keys()))   
print("\nAutovetores: ", [list(tup[2][0]) for tup in A.eigenvects()])  


Autovalores:  [-sqrt(17)/2 - 3/2, -3/2 + sqrt(17)/2]

Autovetores:  [[-2/(-sqrt(17)/2 + 3/2), 1], [-2/(3/2 + sqrt(17)/2), 1]]


### Exercício 5 - Calcule o Eigendecomposition da matriz abaixo.

Uma eigendecomposition é calculada em uma matriz quadrada usando um algoritmo iterativo eficiente através de funções do NumPy.

Frequentemente, um autovalor é encontrado primeiro, então um autovetor é encontrado para resolver a equação como um conjunto de coeficientes.

A eigendecomposition pode ser calculada no NumPy usando a função eig(). A eigendecomposition é calculada na matriz retornando os autovalores e autovetores.

In [5]:
# Solução
from numpy import array
from numpy.linalg import eig

# Define a matriz
A = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)

# Calcula eigendecomposition
values, vectors = eig(A)

# Print
print("\nAutovalores: ", values)
print("\nAutovetores: ",vectors)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Autovalores:  [ 1.61168440e+01 -1.11684397e+00 -9.75918483e-16]

Autovetores:  [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


### Exercício 6 - Confirme que um vetor é de fato um autovetor de uma matriz.

Fazemos isso multiplicando o autovetor candidato pelo autovetor e comparando o resultado com o autovalor.

Primeiro, definiremos uma matriz e calcularemos os autovalores e os autovetores. Vamos então testar se o primeiro vetor e valor são de fato um autovalor e um autovetor para a matriz. Nós sabemos que eles são, mas é um bom exercício.

Os autovetores são retornados como uma matriz com as mesmas dimensões que a matriz pai, onde cada coluna é um autovetor, isto é, o primeiro autovetor é o vetor [:, 0]. Os autovalores são retornados como uma lista, onde os índices de valor na matriz retornada são pareados com autovetores pelo índice da coluna, por exemplo. o primeiro autovalor em valores [0] é emparelhado com o primeiro autovetor em vetores [:, 0].

O exemplo multiplica a matriz original pelo primeiro autovetor e a compara ao primeiro autovetor multiplicado pelo primeiro autovalor.

Executar o exemplo imprime os resultados dessas duas multiplicações que mostram o mesmo vetor resultante, como seria de se esperar.

In [6]:
# Solução
from numpy import array
from numpy.linalg import eig

# Define a matriz
A = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Calcula eigendecomposition
values, vectors = eig(A)

# Confirmando o primeiro eigenvector
B = A.dot(vectors[:, 0])
print(B)
C = vectors[:, 0] * values[0]
print(C)

[ -3.73863537  -8.46653421 -13.19443305]
[ -3.73863537  -8.46653421 -13.19443305]


### Exercício 7 - Com base nos autovalores e autovetores, reconstrua a matriz original.

Podemos inverter o processo e reconstruir a matriz original, recebendo apenas os autovetores e autovalores.

Primeiro, a lista de autovetores deve ser convertida em uma matriz, onde cada vetor se torna uma linha. Os autovalores precisam ser organizados em uma matriz diagonal. A função NumPy diag() pode ser usada para isso.

Em seguida, precisamos calcular o inverso da matriz do vetor próprio, o que podemos alcançar com a função invPP (NumPy). Finalmente, esses elementos precisam ser multiplicados junto com a função dot().

O exemplo calcula os autovalores e os autovetores novamente e os utiliza para reconstruir a matriz original.

A execução do exemplo primeiro imprime a matriz original e, em seguida, a matriz reconstruída a partir de autovalores e autovetores correspondentes à matriz original.

In [7]:
# Solução

from numpy import diag
from numpy import dot
from numpy.linalg import inv
from numpy import array
from numpy.linalg import eig

# Define a Matriz
A = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nMatriz Original:\n", A)

# Calcula autovalofes e autovetores
values, vectors = eig(A)

# Cria a matriz de autovetores
Q = vectors

# Cria a inversa da matriz de autovetores
R = inv(Q)

# Cria a matriz diagonal dos autovalores
L = diag(values)

# Reconstrói a matriz original
B = Q.dot(L).dot(R)
print("\nMatriz Original Reconstruída:\n", B)


Matriz Original:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Matriz Original Reconstruída:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


### Exercício 8 - Você encontra abaixo o link de um repositório no Github para uma app em Python de uma Calculadora de Álgebra Linear, que apresenta via web a possibilidade de fazer muitos dos cálculos que estudamos até aqui no curso. Todo o código está em Python sendo uma excelente fonte de material de referência de estudo.

Faça o download do repositório para sua máquina e estude os códigos apresentados.

https://github.com/subram43/linear-algebra-calculator

## Fim