# <font color='blue'>Data Science Academy</font>
# <font color='blue'>Matemática Para Machine Learning</font>

## Lista de Exercícios  - Capítulo 7

O objetivo desta lista de exercícios é você praticar os principais conceitos estudados neste capítulo, ao mesmo tempo que desenvolve suas habilidades em lógica de programação com a linguagem Python. 

Caso tenha dúvidas, isso é absolutamente normal e faça um trabalho de pesquisa a fim de relembrar o formato das operações matemáticas.

Quando encontrar o formato de uma operação que resolva o exercício proposto, use a linguagem Python para representar esta operação. Em essência, é assim que aplicamos Matemática Para Machine Learning, construindo algoritmos e representando esses algoritmos em linguagem de programação.

Divirta-se!!

### Exercício 1 - Resolva o sistema de equações:

# 1x + 1y = 18
# 2x + 4y = 24

In [6]:
# Solução
import numpy as np

A = np.array([[1,1],[2,4]])
Ax = np.array([[18,1],[24,4]])
Ay = np.array([[1,18],[2,24]])

detA = np.linalg.det(A)
detAx = np.linalg.det(Ax)
detAy = np.linalg.det(Ay)

x = detAx / detA
y = detAy / detA

print('Valor de x:', x)
print('Valor de y:', y)

Valor de x: 24.000000000000004
Valor de y: -6.0


In [5]:
import numpy as np
a = np.array([[1,1],[2,4]]) 
b = np.array([[18],[24]])
np.linalg.solve(a,b)

array([[24.],
       [-6.]])

### Exercício 2 - Resolva o sistema linear abaixo:

# x+y+z = 2

# 2x-6y-z=-1

# 3x-2z=8

Dica: organize os coeficientes na orientação das linhas no sistema linear.

In [9]:
# Solução 
import numpy as np

A = np.array([[1,1,1],[2,-6,-1],[3,0,-2]])
Ax = np.array([[2,1,1],[-1,-6,-1],[8,0,-2]])
Ay = np.array([[1,2,1],[2,-1,-1],[3,8,-2]])
Az = np.array([[1,1,2],[2,-6,-1],[3,0,8]])

detA = np.linalg.det(A)
detAx = np.linalg.det(Ax)
detAy = np.linalg.det(Ay)
detAz = np.linalg.det(Az)

x = detAx / detA
y = detAy / detA
z = detAz / detA

print('Valor de x:', x)
print('Valor de y:', y)
print('Valor de z:', z)

Valor de x: 2.0000000000000004
Valor de y: 1.0
Valor de y: -0.9999999999999996


### Exercício 3 - Resolva o sistema linear abaixo:

# x+y+z = 2

# 2x-6y-z=-1

# 3x-2z=8

Dica: organize os coeficientes na orientação das colunas no sistema linear.

In [11]:
# Solução 
import numpy as np
a = np.array([[1,1,1],[2,-6,-1],[3,0,-2]]) 
b = np.array([[2],[-1],[8]])
np.linalg.solve(a,b)

[[ 2.]
 [ 1.]
 [-1.]]


### Exercício 4 - Resolva o sistema linear abaixo usando o método da matriz inversa:

# x+y+z = 2

# 2x-6y-z=-1

# 3x-2z=8

In [12]:
# Solução 
A = np.array([[1,1,1],[2,-6,-1],[3,0,-2]])
B = np.array([[2],[-1],[8]])

A_I = np.linalg.inv(A)

X = np.dot(A_I, B)

print(X)

[[ 2.]
 [ 1.]
 [-1.]]


### Exercício 5 - Resolva o sistema linear abaixo:

# 3x+2y-4z+t = 30

# 2x+3y+3z+2t=150

# 5x-3y+z-5t=140

# x+y+z+t=60

In [13]:
# Solução 
A = np.array([[3,2,-4,1],[2,3,3,2],[5,-3,1,-5],[1,1,1,1]])
B = np.array([[30],[150],[140],[60]])

A_I = np.linalg.inv(A)

X = np.dot(A_I, B)

print(X)

[[ 3.00000000e+01]
 [ 1.00000000e+01]
 [ 2.00000000e+01]
 [-1.42108547e-14]]


### Exercício 6 (Desafio) - Desenvolva uma função em Python que obtenha o mesmo resultado da função solve() abaixo.

Dica: sua função deve receber a equação como parâmetro e não as matrizes.

In [4]:
import numpy as np
a = np.array([[3,5],[12,-3]]) 
b = np.array([[29],[24]])
np.linalg.solve(a,b)

array([[3.],
       [4.]])

In [5]:
# Solução 
from sympy import *

def mysolve(eq, var=('x', 'y')):
    import re

    var_re = re.compile(r'(\+|\-)\s*(\d*)\s*\*?\s*(x|y)')
    const_re = re.compile(r'(\+|\-)\s*(\-?\d+)$')

    constants, eqns, coeffs, default  = [],[], {'x': [], 'y': []}, {'': '1'}

    for e in eq.split(';'):
        eq1 = e.replace("="," - ").strip()
        print('eq1',eq1)
        if not eq1.startswith('-'):
            eq1 = '+' + eq1
        eqns.append(eq1)
        print('eqns',eqns)

    var_eq1, var_eq2 = map(var_re.findall, eqns)

    constants = [-1*int(x[0][1]) for x in map(const_re.findall, eqns)]
    [coeffs[x[2]].append(int((x[0]+ default.get(x[1], x[1])).strip())) for x in (var_eq1 + var_eq2)]
    
    ycoeff = coeffs['y']
    xcoeff = coeffs['x']

    # Ajuste as equações para receber y e resolva para x
    if ycoeff[0]*ycoeff[1] > 0:
        ycoeff[1] *= -1
        xcoeff[0] *= ycoeff[1]
        constants[0] *= -1*ycoeff[1]        
    else:
        xcoeff[0] *= -1*ycoeff[1]
        constants[0] *= ycoeff[1]
        
    xcoeff[1] *= ycoeff[0]
    constants[1] *= -1*ycoeff[0]

    # Obtém x
    xval = sum(constants)*1.0/sum(xcoeff)

    # Agora resolva para y usando o valor de x
    z = eval(eqns[0],{'x': xval, 'y': 1j})
    yval = -z.real*1.0/z.imag

    return (xval, yval)


In [6]:
# Solução 

mysolve('3*x + 5*y = 29; 12*x - 3*y = 24')

eq1 3*x + 5*y  -  29
eqns ['+3*x + 5*y  -  29']
eq1 12*x - 3*y  -  24
eqns ['+3*x + 5*y  -  29', '+12*x - 3*y  -  24']


(3.0, 4.0)

## Fim