# <font color='blue'>Data Science Academy</font>
# <font color='blue'>Matemática Para Machine Learning</font>

## Lista de Exercícios  - Capítulo 4

O objetivo desta lista de exercícios é você praticar os principais conceitos estudados neste capítulo, ao mesmo tempo que desenvolve suas habilidades em lógica de programação com a linguagem Python. 

Caso tenha dúvidas, isso é absolutamente normal e faça um trabalho de pesquisa a fim de relembrar o formato das operações matemáticas.

Quando encontrar o formato de uma operação que resolva o exercício proposto, use a linguagem Python para representar esta operação. Em essência, é assim que aplicamos Matemática Para Machine Learning, construindo algoritmos e representando esses algoritmos em linguagem de programação.

A maioria das pessoas considera a Matemática e a Física, assustadoras bestas das quais é melhor manter a distância. Computadores, no entanto, podem nos ajudar a domar a complexidade e a aritmética tediosa das manipulações associadas a esses assuntos. De fato, Matemática e Física são muito mais acessíveis, uma vez que você tem o poder de computadores do seu lado.

Divirta-se!!

### Exercício 1 - Considerando os vetores v [1, 2] e w [2, 1], crie um script Python que faça a soma dos vetores. Não use funções de pacotes prontos, somente a linguagem Python pura e suas funções, se necessário.

Dica: A função zip() pode ajudá-lo.

In [1]:
# Solução

vetor1 = [1, 2]
vetor2 = [2, 1]

def soma_vetor(v, w):
    soma = [v_i + w_i for v_i, w_i in zip(v, w)]
    return soma

soma_vetor(vetor1, vetor2)

[3, 3]

### Exercício 2 - Considerando os vetores v [1, 2] e w [2, 1], crie um script Python que faça a subtração dos vetores. Não use funções de pacotes prontos, somente a linguagem Python pura e suas funções, se necessário.

Dica: A função zip() pode ajudá-lo.

In [2]:
# Solução

vetor1 = [1, 2]
vetor2 = [2, 1]

def subtrai_vetor(v, w):
    sub = [v_i - w_i for v_i, w_i in zip(v, w)]
    return sub

subtrai_vetor(vetor1, vetor2)

[-1, 1]

### Exercício 3 - Considerando o escalar e vetor abaixo, crie uma função que receba os 2 como parâmetro e multiplique o vetor pelo escalar. Use apenas Python puro.

Dica: List Comprehension pode ajudá-lo aqui. O curso de Python Fundamentos oferece exemplos deste recurso.

In [3]:
# Solução

num = 3
vetor = [1, 2, 3]

def scalar_multiply(c, v):
    resultado = [c * v_i for v_i in v]
    return resultado

scalar_multiply(num, vetor)

[3, 6, 9]

### Exercício 4 - Considerando os 2 vetores abaixo, crie uma função Python que faça o dot product entre os 2 vetores e retorne apenas um valor escalar.

In [4]:
# Solução

vetor1 = [1, 2]
vetor2 = [2, 1]

def dot(v, w):
    resultado = sum(v_i * w_i for v_i, w_i in zip(v, w))
    return resultado

dot(vetor1, vetor2)

4

### Exercício 5 - Resolva o exercício anterior usando a função dot() do NumPy

In [5]:
# Solução

import numpy as np

vetor1 = [1, 2]
vetor2 = [2, 1]

np.dot(vetor1, vetor2)

4

### Exercício 5.1 - Considerado os vetores abaixo, encontre o cross product entre eles, usando Python puro e NumPy.

In [6]:
# Solução

vetor1 = [1, 2, 3]
vetor2 = [3, 2, 1]

def my_cross(a, b):
    c = [a[1]*b[2] - a[2]*b[1],
         a[2]*b[0] - a[0]*b[2],
         a[0]*b[1] - a[1]*b[0]]

    return c

my_cross(vetor1, vetor2)

[-4, 8, -4]

In [7]:
# Solução

import numpy as np

vetor1 = [1, 2, 3]
vetor2 = [3, 2, 1]

np.cross(vetor1, vetor2)

array([-4,  8, -4])

### Exercício 6 - Crie uma lista em Python com 3 dimensões, preenchida com zeros.

Dica: a função pprint do pacote pprint permite imprimir uma lista tridimensional de forma mais legível.

In [8]:
# Solução

import pprint
n = 3
vetor = [[[0 for k in range(n)] for j in range(n)] for i in range(n)]
type(vetor)
pprint.pprint(vetor)

[[[0, 0, 0], [0, 0, 0], [0, 0, 0]],
 [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
 [[0, 0, 0], [0, 0, 0], [0, 0, 0]]]


### Exercício 7 - Considerando o vetor criado no item anterior, altere o valor na posição nas coordenadas (2, 1, 0) para 92.

In [9]:
# Solução

vetor[2][1][0] = 92
pprint.pprint(vetor)

[[[0, 0, 0], [0, 0, 0], [0, 0, 0]],
 [[0, 0, 0], [0, 0, 0], [0, 0, 0]],
 [[0, 0, 0], [92, 0, 0], [0, 0, 0]]]


### Exercício 8 - Considere o vetor multidimensional A abaixo. Transforme-o em um vetor de uma única dimensão, com todos os elementos ordenados na mesma sequência do vetor original.

Dica: Esta operação é chamada de flatten do vetor (algo como "achatar" um vetor), sendo uma das operações de pré-processamento mais comum em modelos de Deep Learning para Visão Computacional. NumPy oferece uma função para isso.

In [10]:
# Solução

import numpy as np

A = np.array([[[ 0,  1],
               [ 2,  3],
               [ 4,  5],
               [ 6,  7]],
              [[ 8,  9],
               [10, 11],
               [12, 13],
               [14, 15]],
              [[16, 17],
               [18, 19],
               [20, 21],
               [22, 23]]])

print("\nVetor multidimensional original:\n\n", A)

Flattened_A = A.flatten()
print("\n\nVetor flattened:\n\n", Flattened_A)


Vetor multidimensional original:

 [[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]


Vetor flattened:

 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


### Exercício 9 - Considere o vetor multidimensional A abaixo. Transforme-o em um vetor de uma única dimensão, com todos os elementos ordenados na mesma sequência do vetor original. Use a função ravel() do NumPy.

A função ravel() possui o parâmetro "order" que pode ser "C", "F", "A" ou "K". Qual a diferença entre usar os parâmetros C e F?

In [11]:
# Solução

import numpy as np

A = np.array([[[ 0,  1],
               [ 2,  3],
               [ 4,  5],
               [ 6,  7]],
              [[ 8,  9],
               [10, 11],
               [12, 13],
               [14, 15]],
              [[16, 17],
               [18, 19],
               [20, 21],
               [22, 23]]])

print("\nVetor multidimensional original:\n\n", A)

Flattened_A = A.ravel(order="C")
print("\n\nVetor flattened com Parâmetro C:\n\n", Flattened_A)
Flattened_A = A.ravel(order="F")
print("\n\nVetor flattened com Parâmetro F:\n\n", Flattened_A)


Vetor multidimensional original:

 [[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]


Vetor flattened com Parâmetro C:

 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


Vetor flattened com Parâmetro F:

 [ 0  8 16  2 10 18  4 12 20  6 14 22  1  9 17  3 11 19  5 13 21  7 15 23]


### Exercício 10 - Calcule o Inner e Outer product dos vetores abaixo.

In [12]:
# Solução

import numpy as np

vetor1 = [1, 2]
vetor2 = [2, 1]

innerProduct = np.inner(vetor1, vetor2)
outerProduct = np.outer(vetor1, vetor2)

print(innerProduct)
print(outerProduct)

4
[[2 1]
 [4 2]]


## Fim